---
title: "5261-Project"
author: "Bo Peng"
date: "April 17, 2017"
output:
  pdf_document: default
  html_document: default
---

Read data
```{r}
library(zoo)
library(stats)
LIBOR <- read.csv("../data/1-Month_LIBOR_daily.csv", header = TRUE, as.is = T)
LIBOR[,1] <- as.Date(LIBOR[,1], "%m/%d/%Y")
SHIBOR <- read.csv("../data/SHIBOR.csv", header = TRUE, as.is = T)
SHIBOR[,1] <- as.Date(SHIBOR[,1], "%m/%d/%Y")
CSI300 <- read.csv("../data/CSI300_daily.csv", header = TRUE, as.is = T)
CSI300[,1] <- as.Date(CSI300[,1], "%m/%d/%Y")
GSPC <- read.csv("../data/S&P500(^GSPC)_daily.csv", header = TRUE, as.is = T)
GSPC[,1] <- as.Date(GSPC[,1], "%m/%d/%Y")
EX <- read.csv("../data/ExRate.csv", header = TRUE, as.is = T)
EX[,1] <- as.Date(EX[,1], "%m/%d/%Y")
TRADE <- read.csv("../data/Trade.csv", header = TRUE, as.is = T)
TRADE[,1] <- as.Date(as.yearmon(TRADE[,1], "%Y/%m"))
TRADE <- TRADE[order(TRADE[,1]),]
M_US <- read.csv("../data/m1m2_US.csv", header = TRUE, as.is = T)
M_US[,1] <- as.Date(as.yearmon(M_US[,1], "%Y-%m"))
M_CN <- read.csv("../data/m1m2_China.csv", header = TRUE, as.is = T)
M_CN[,1] <- as.Date(as.yearmon(M_CN[,1], "%Y-%m"))
M_CN <- M_CN[order(M_CN[,1]),]
LIBOR <- LIBOR[-nrow(LIBOR),]
TRADE[1,1] <- TRADE[1,1]+1
M_CN[1,1] <- M_CN[1,1]+1
M_CN <- M_CN[-c(nrow(M_CN), nrow(M_CN)-1), ]
M_US[1,1] <- M_US[1,1]+1
```

Combine into main dataframe
```{r}
DATE <- seq(min(LIBOR[,1]), max(LIBOR[,1]), by="days")
DATE <- data.frame(DATE)
main <- merge(CSI300, DATE, by.x='Date', by.y='DATE', all.x=T, all.y=T)
main <- merge(main, EX, by.x='Date', by.y='Date', all.x=T, all.y=T)
main <- merge(main, GSPC, by.x='Date', by.y='Date', all.x=T, all.y=T)
main <- merge(main, LIBOR, by.x='Date', by.y='DATE', all.x=T, all.y=T)
main <- merge(main, M_CN, by.x='Date', by.y='Time.Period', all.x=T, all.y=T)
main <- merge(main, M_US, by.x='Date', by.y='Time.Period', all.x=T, all.y=T)
main <- merge(main, SHIBOR, by.x='Date', by.y='Date', all.x=T, all.y=T)
colnames(main) <- c("Date", "CSI300", "RMBperUSD", "GSPC", "LIBOR", "m2_CN", "m1_CN", "m1_US", "m2_US", "SHIBOR")
main <- main[, c("Date", "RMBperUSD", "SHIBOR", "LIBOR", "CSI300", "GSPC", "m1_CN", "m2_CN", "m1_US", "m2_US")]
```

Use interpolation to fill missing spaces
```{r, warning=FALSE}
for (i in 4:10) {
  main[,i][is.na(main[,i])] <- "."
  main[,i] <- as.numeric(paste(main[,i]))
}

for (i in 2:6) {
  main[3:nrow(main),i] <- na.approx(main[3:nrow(main),i])
}

for (j in 7:10) {
  for (i in 1:nrow(main)) {
    if (is.na(main[i,j])) {
      k <- max(which(is.na(main[1:i,j]) == FALSE))
      main[i,j] <- main[k,j]
    }
  }
}

main <- main[-c(1,2),]
main <- main[3145:3709,]
save(main, file = "main.RData")
```

Plots
```{r}
plot(x = main$Date, y = main$RMBperUSD, type = "l", xaxt = "n", ylab = "RMB per USD", main = "Exchange Rate")
axis(1, main$Date, format(main$Date, "%b %Y"), cex.axis = .8)
```

```{r}
par(mfrow=c(2, 1))
plot(x = main$Date, y = main$SHIBOR, type = "l", xaxt = "n", xlab = "", ylab = "SHIBOR")
axis(1, main$Date, format(main$Date, "%b %Y"), cex.axis = .8)
plot(x = main$Date, y = main$LIBOR, type = "l", xaxt = "n", xlab = "Date", ylab = "LIBOR")
axis(1, main$Date, format(main$Date, "%b %Y"), cex.axis = .8)
```

```{r}
plot(x = main$Date, y = main$CSI300, type = "l", xaxt = "n", ylab = "CSI300", main = "China Shanghai Index 300")
axis(1, main$Date, format(main$Date, "%b %Y"), cex.axis = .8)
```

```{r}
plot(x = main$Date, y = main$GSPC, type = "l", xaxt = "n", ylab = "GSPC", main = "Standard & Poor 500")
axis(1, main$Date, format(main$Date, "%b %Y"), cex.axis = .8)
```

```{r, warning=FALSE}
m2_CN_ad <- c(0, log(diff(main$m2_CN)))
m2_US_ad <- c(0, log(diff(main$m2_US)))
m <- cbind(main$Date, m2_CN_ad, m2_US_ad)
m <- as.data.frame(m)
m[,1] <- as.Date(m[,1])
m <- m[m$m2_CN_ad != (-Inf),]
m <- m[m$m2_CN_ad != 0,]
m <- m[m$m2_US_ad != (-Inf),]
m <- na.omit(m)
```

```{r}
par(mfrow=c(2, 1))
plot(x= m$V1, y = m$m2_CN_ad, type = "l", xaxt = "n", ylab = "Log Difference", main = "Rate of Increasae of China's M2", xlab = "")
axis(1, m$V1, format(m$V1, "%b %Y"), cex.axis = .8)
plot(x= m$V1, y = m$m2_US_ad, type = "l", xaxt = "n", ylab = "Log Difference", main = "Rate of Increasae of US's M2", xlab = "Date")
axis(1, m$V1, format(m$V1, "%b %Y"), cex.axis = .8)
```


Scale regressors
```{r}
main[,3:8] <- scale(main[,3:8])
```

Divide dataset into training and test sets
```{r}
train <- main[1:510,]
test <- main[511:565,]
```





Arima model with regressors
```{r, warning=FALSE}
library(zoo)
library(forecast)

m <- auto.arima(train$RMBperUSD, xreg = train[,3:10])
m
```

Plot residuals
```{r}
plot(m$residuals)
```

Use model to forecast over test set
```{r}
pred <- forecast(m, xreg = test[,3:10], h = 55)
plot(pred, main = "Prediction using ARIMA model with regressors")
```

Calculate mean test error
```{r}
forecasted <- as.numeric(pred$mean)
actual <- test$RMBperUSD
errors <- (forecasted - actual)^2
mse <- mean(errors)
mse
```

